name: Python application

on: [push]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10']

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install poetry
      run: |
        python -m pip install --upgrade pip poetry

    - name: View poetry --help
      run: poetry --help

    - name: Regenerate poetry.lock
      run: |
        poetry lock  # Regenera o arquivo poetry.lock
        git add poetry.lock
        git commit -m "Update poetry.lock"
        git push  # Envia a atualização do poetry.lock de volta para o repositório

    - name: Install dependencies
      run: poetry install

    - name: Test
      run: |
        poetry run python manage.py test